### ISSUE TITLE
docClose issue on iPad

### ISSUE THREAD

**Issue by DanielM-1993** [andreknieriem/simplelightbox#41] opened 2016-04-25 15:13 UTC
Hello,

I have implemented your simple lightbox for use on a responsive and mobile friendly website however I am having problems with the docClose functionality when testing on an iPad. I have tested the functionality on an Android mobile, Windows 7 PC, Windows 10 PC and Macbook and for all of these clicking away from the image in the lightbox will cause it to close like expected however this functionality is not working for me on an iPad.

Are there any suggestions?

Note: I am running iOS 9.3.1 and using Safari

Update: I have noticed that you can close the lightbox if you click on the border between the image and the overlay but it has to be directly on the border, any further away and the functionality is lost.

**Comment by andreknieriem** [comment] 2016-04-26 18:37
Hey thanks for feedback. Will try to find a bugfix for it. Does clicking on the overlay work?

**Comment by DanielM-1993** [comment] 2016-04-27 08:48
Clicking the overlay on a Windows dekstop, laptop or Macbook works. So does clicking the overlay on an Android mobile/tablet. iPad is the only one where clicking the overlay doesn't work.

**Comment by andreknieriem** [comment] 2016-04-27 13:17
Hey, does everything else work? For example next/prev Buttons and so on? I only can test it on an old ipad 3 in the next days, but I can't imagine what the problem is.

**Comment by DanielM-1993** [comment] 2016-04-28 08:00
Yeah, navigation buttons work fine. I have a feeling that iOS/Safari doesn't register click events in the same way that everything else does. It might be a similar issue.

**Comment by andreknieriem** [comment] 2016-04-28 18:53
Changed something in the code. Could see the preview here:

http://andreknieriem.de/simple-lightbox-dev/ Please check it out with your iOS Device.

**Comment by DanielM-1993** [comment] 2016-04-29 14:53
I've had a look at the preview in Google Chrome and Safari on the iPad again and the touch overlay to close functionality is still not working. May I ask what solution you tried?

**Comment by andreknieriem** [comment] 2016-05-02 08:27
So on my iPhone it works now. Can you please it on my dev page:
http://andreknieriem.de/simple-lightbox-dev/ 

Best regards

**Comment by andreknieriem** [comment] 2016-05-03 06:35
I close this issue. If it still doesn't work for you, please let me know.

**Closed by andreknieriem** 2016-05-03 06:35 UTC
Labels: bug

**Comment by DanielM-1993** [comment] 2016-05-03 10:51
Works perfectly! Thank you very much for the quick fix.
