### ISSUE TITLE
Lightbox not working if the image URL have GET parameter

### ISSUE THREAD

**Issue by Yannick-Valentin** [andreknieriem/simplelightbox#19] opened 2015-12-18 10:29 UTC
If the link URL contains GET parameters (e.g. ?param=foo), the lightbox doesn't work.

Example : http://codepen.io/yvalentin/pen/mVPBKg

**Comment by andreknieriem** [comment] 2015-12-18 13:40
Hey, this is duplicate of https://github.com/andreknieriem/simplelightbox/issues/7. Just use fileExt; false as option.

**Comment by Yannick-Valentin** [comment] 2015-12-18 13:56
Hi Andre, great, it works as expected, thank you for your quick reply !

**Closed** 2016-01-08 12:31 UTC
Labels: duplicate
