### ISSUE TITLE
disableScroll option does not work

### ISSUE THREAD

**Issue by sharaputo** [andreknieriem/simplelightbox#249] opened 2021-08-26 08:50 UTC
disableScroll option is set to true by default, but it does not work even in case I set it to true in options. Page is scrolling behind.

**Comment by andreknieriem** [comment] 2021-08-31 09:12
Does this happen on the documentation page aswell? https://simplelightbox.com/ I cannot reproduce this on windows right now.

**Comment by sharaputo** [comment] 2021-08-31 09:15
Yes. I am running macos Big Sur now and the problem is still here. I’ve checked Mozilla and Safari, same thing.

**Comment by andreknieriem** [comment] 2021-09-06 08:19
Should be fixed in 2.8.1

**Closed by andreknieriem** 2021-09-06 08:19 UTC
Labels: bug
