### ISSUE TITLE
after ajax completed refresh is not working

### ISSUE THREAD

**Issue by Bronxphoneix** [andreknieriem/simplelightbox#305] opened 2023-02-25 18:21 UTC
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'HTML > BODY:nth-child(2) > SECTION#gallery:nth-child(1) > DIV.container:nth-child(1) > DIV.gallery.gallery_wrapper:nth-child(2) > DIV#1.gallery_item:nth-child(2) > A:nth-child(1) img' is not a valid selector.
    at Image.<anonymous> (http://localhost/galeri/inc/simpleLightbox.js:593:134)

after ajax complete, refreshing the lightbox (opened lighttbox ) and dont work navigation etc. console has there error.

`var lightbox = new SimpleLightbox('.gallery_item a', {});
.
.
.
.
.
.
.success:function(data){
					if(data != 0){
                    setTimeout(function() {
                    $('.loader').remove();
                    $('.gallery_wrapper').append(data);
					lightbox.refresh();
                   },1000);
                    }`

**Comment by andreknieriem** [comment] 2023-03-29 06:20
Can you try this with the latest version? 2.13.0. Thanks

**Comment by jbator** [comment] 2023-04-24 08:57
Hi, I have similar issue in version 2.13.0
When some lightbox window is opened and some ajax job is done and lightbox.refresh() method is called in the backgroud, my opened image is closed and all lightbox is crashing with error:  

`caught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
 
Is there any way to initialize lightbox only on new loaded elements?

**Comment by Bronxphoneix** [comment] 2023-04-24 11:44
yes

Jarek ***@***.***>, 24 Nis 2023 Pzt, 11:57 tarihinde şunu
yazdı:

**Comment by andreknieriem** [comment] 2023-04-24 12:06
Hi. Do you have any example online for me to test it? Can't reproduce.

**Comment by jbator** [comment] 2023-04-24 13:44
@andreknieriem Yes, simple demo is here: http://jbator.pl/test.html
Just click MORE ELEMENTS link, then click image thumbnail which opens simplelightbox, after 5 seconds ajax is finished and refresh method is called - then error occurs...

**Comment by andreknieriem** [comment] 2023-05-05 12:04
Ok. That is an error with overlay: false - option. You have disabled the overlay, but the fadeout wants to remove it. I added an if statement for. Will be fixed in the next release.

**Closed** 2023-05-05 12:15 UTC
Labels: bug, input needed
