### ISSUE TITLE
image scale bug

### ISSUE THREAD

**Issue by andrconstruction** [andreknieriem/simplelightbox#122] opened 2019-02-08 06:34 UTC
After update to 1.16. Images wich has the size bigger than screen not scale during opening otherwise all work as expected

![image](https://user-images.githubusercontent.com/7435330/52462478-4ed88180-2b84-11e9-96dd-16a54a6cd0af.png)

**Comment by andreknieriem** [comment] 2019-02-08 07:25
Hey there. I'm not able to reproduce. Did you update the CSS? There were changes for the pinch feature and the wrapper around gets the sizes now.

**Comment by slatinsky** [comment] 2019-02-08 08:34
I had the same problem. Updating CSS fixed it for me.

**Comment by andreknieriem** [comment] 2019-02-08 08:39
Alright. I close this for now ;)

**Closed by andreknieriem** 2019-02-08 08:39 UTC
Labels: invalid

**Comment by andrconstruction** [comment] 2019-02-08 18:07
Yes indeed, used old styles
