### ISSUE TITLE
Query strings seem to stop the plugin from working

### ISSUE THREAD

**Issue by appel** [andreknieriem/simplelightbox#75] opened 2017-07-15 01:59 UTC
My CMS uses a cache busting feature that automatically appends a timestamp to the end of an image. Somehow this seems to stop the plugin from working.

For example, this break the plugin:
````
<a href="image.jpg?1499610298" class="lightbox"><img src="thumb.jpg?1499610298"></a>
````
But this works fine:
````
<a href="image.jpg" class="lightbox"><img src="thumb.jpg?1499610298"></a>
````

Note the `?1499610298` query string in the anchor href.

Here's how I call simpleLightbox:

````
$('a.lightbox').simpleLightbox();
````

**Comment by appel** [comment] 2017-07-15 02:28
Removing `$` from from line 141 [(see here)](https://github.com/appel/simplelightbox/commit/cc1eaa1331bf5482ad64b639d09b371dba85c74f) appears to have fixed the problem, but I'm by no means a regex or JS expert, so no idea if that broke something else.

**Comment by andreknieriem** [comment] 2017-07-17 13:47
Hey, this is a duplicate of https://github.com/andreknieriem/simplelightbox/issues/59. It's because if the file-ending function. If you set fileExt: false in your option, the lightbox will work again. There is no fix right now for images with query string and fileExt check enabled. I will check this for the new version.

**Closed by andreknieriem** 2017-07-17 13:47 UTC

**Comment by appel** [comment] 2017-07-17 13:53
Apologies, completely missed the dupe. And thank you for the plugin!
